@startuml TPC

start
:Определить последовательность S[11];
while (Введён 11 элемент?) is (нет)
    :Запросить элемент<
    :Добавить в последовательность;
endwhile (да)
:l = 0 левая граница последовательности;
:r = 11 - 1 правая граница последовательности;
while (l < r) is (да)
    :менять местами S[l] и S[r];
    :l++ и r--;
endwhile (нет)
:i = 0;
while (i < 11) is (да)
    :f = sqrt(fabs(S[i])) + 5 * pow(S[i], 3);
    if (f > 400) then (да)
        :"Значение функции больше 400">
    else (нет)
        : f >
    endif
:i++;
endwhile(нет)
stop

@enduml

