@startuml TPC

start
:Запросить 11 чисел у пользователя>
:Записать числа в последовательность П<
:Инвертировать последовательность П;
while (конец последовательности?) is (нет)
    :f = sqrt(fabs(Х)) + 5 * pow(Х, 3);
    if (f > 400) then (да)
        :Значение функции больше 400>
    else (нет)
        : f >
    endif
endwhile(да)
stop

@enduml

' sqrt(fabs(Х)) + 5 * pow(Х, 3)